title: Anderson Tami-Patiño
logo: /assets/img/E89A7191.JPG
description: Visiting Assistant Professor. 
description: St Mary's College of Maryland
description: Phd in Economics.
description: Florida International University
description: Economics of Education, conflict and child labor.
theme: jekyll-theme-minimal
